export const KNOWLEDGE_CATEGORIES = {
  ABOUT: "ABOUT",
  FAQ: "FAQ",
  SERVICE: "SERVICE",
  POLICY: "POLICY",
  LOCATION_INFO: "LOCATION_INFO",
  CUSTOM: "CUSTOM",
} as const;

export type KnowledgeCategory =
  (typeof KNOWLEDGE_CATEGORIES)[keyof typeof KNOWLEDGE_CATEGORIES];

export const ALL_KNOWLEDGE_CATEGORIES: KnowledgeCategory[] = [
  KNOWLEDGE_CATEGORIES.ABOUT,
  KNOWLEDGE_CATEGORIES.FAQ,
  KNOWLEDGE_CATEGORIES.SERVICE,
  KNOWLEDGE_CATEGORIES.POLICY,
  KNOWLEDGE_CATEGORIES.LOCATION_INFO,
  KNOWLEDGE_CATEGORIES.CUSTOM,
];
